# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /media/ben/STOCK/conda_build_tuto, last modified Tue Sep  3 18:11:02 2019
# ------------------------------------------------

package:
    name: rappas
    version: '1.11'
source:
    git_rev: v1.11
    git_url: https://github.com/blinard-BIOINFO/RAPPAS.git
build:
    string: '0'
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - alsa-lib 1.1.5 h516909a_1001
        - ant 1.10.0 0
        - ca-certificates 2019.6.16 hecc5488_0
        - curl 7.65.3 hf8cf82a_0
        - expat 2.2.5 he1b5a44_1003
        - fontconfig 2.13.1 h86ecdb6_1001
        - freetype 2.10.0 he983fc9_1
        - gettext 0.19.8.1 hc5be6a0_1002
        - giflib 5.1.7 h516909a_1
        - git 2.23.0 pl526hce37bd2_0
        - icu 64.2 he1b5a44_1
        - jpeg 9c h14c3975_1001
        - krb5 1.16.3 h05b26f9_1001
        - lcms2 2.9 h2e4bb80_0
        - libcurl 7.65.3 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.37 hed695b0_0
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtiff 4.0.10 h57b8799_1003
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.9 hee79883_5
        - lz4-c 1.8.3 he1b5a44_1001
        - ncurses 6.1 hf484d3e_1002
        - openjdk 11.0.1 h46a85a0_1017
        - openssl 1.1.1c h516909a_0
        - perl 5.26.2 h516909a_1006
        - pthread-stubs 0.4 h14c3975_1001
        - tk 8.6.9 hed695b0_1002
        - xorg-fixesproto 5.0 h14c3975_1002
        - xorg-inputproto 2.3.2 h14c3975_1002
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libx11 1.6.8 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxfixes 5.0.3 h516909a_1004
        - xorg-libxi 1.7.10 h516909a_0
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-libxtst 1.2.3 h14c3975_1002
        - xorg-recordproto 1.14.2 h14c3975_1002
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
        - zstd 1.4.0 h3b9ef0a_0
    run:
        - openjdk >=8.0.144
        - phyml =3.3.20180621
test:
    files:
        - test/150.fasta
        - test/150.newick
        - test/q.fasta
app:
    entry: rappas
    summary: RAPPAS (Rapid Alignment-free Phylogenetic PLacement via Ancestral Sequences)
        is a program dedicated to Phylogenetic Placement of (meta)genomic reads on
        a reference tree. As apposed to previous PP programs, RAPPAS is based on the
        phylo-kmers idea, detailed in tis manuscript and uses a 2 step approach divided
        into a) the database build, and b) the placement itself.
about:
    home: https://github.com/blinard-BIOINFO/RAPPAS
    license: GPL3
    summary: RAPPAS (Rapid Alignment-free Phylogenetic PLacement via Ancestral Sequences)
        is a program dedicated to Phylogenetic Placement of (meta)genomic reads on
        a reference tree. As apposed to previous PP programs, RAPPAS is based on the
        phylo-kmers idea, detailed in tis manuscript and uses a 2 step approach divided
        into a) the database build, and b) the placement itself. The main advantage
        of RAPPAS is that it is alignment free, which means that after step (a) (the
        DB build) is performed, metagenomic reads can be directly placed on a referene
        tree WITHOUT aligning them to the reference alignment on which the tree was
        built (as required by other approaches). The second advantage of RAPPAS is
        its algorithm based on phylo-kmers matches, making its execution time linear
        with respect to the length of the placed sequences.
extra:
    copy_test_source_files: true
    final: true
